flow:
  processors:
    FilterAttribute:
      type: FilterAttribute
      config:
        mode: remove
        attributes: http.headers;internal.tmp
sources:
  ListenHTTP:
    type: ListenHTTP
    config:
      port: "9100"
      path: /
      maxBodyBytes: "16777216"
