flow:
  entryPoints: [tag-env]
  processors:
    tag-env:
      type: UpdateAttribute
      config:
        key: env
        value: dev
    tag-source:
      type: UpdateAttribute
      config:
        key: source
        value: api
    logger:
      type: LogAttribute
      config:
        prefix: flow
    sink:
      type: PutFile
      config:
        outputDir: /tmp/caravan-flow-csharp/output
        namingAttribute: filename
      requires: [content]
  connections:
    tag-env:
      success: [tag-source]
    tag-source:
      success: [logger]
    logger:
      success: [sink]
